### ISSUE TITLE
this._timeout undefined

### ISSUE THREAD

**Issue by esetnik** [sgnl/nodeku#13]
Using the provided sample code:
```
const Nodeku = require('nodeku')

Nodeku()
  .then(device => {
    console.log(`device found at: ${ device.ip() }`)
    // 'xxx.xxx.xxx.xxx:8060'
    return device.apps()
  })
  .then(apps => {
    apps.forEach(app => console.log(app))
    // [{ id, name, type, version }, ...]
  })
  .catch(err => {
    console.error(err.stack)
  })
```

I receive the following error:
```
/xxx/node_modules/nodeku/lib/discovery.js:8
  timeout = timeout || this._timeout || 10000;
                           ^

TypeError: Cannot read property '_timeout' of undefined
    at module.exports (/xxx/node_modules/nodeku/lib/discovery.js:8:28)
    at Object.<anonymous> (/xxx/roku.js:3:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:504:3
```

**Comment by sgnl** [comment]
Thanks for reporting, I will look into it asap
